[package]
name = "mikep/stealawarrior"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Component = "sleitnick/component@2.4.8"
Rodux = "roblox/rodux@3.0.0"
Roact = "roblox/roact@1.4.4"
RoactRodux = "roblox/roact-rodux@0.3.0"
Flipper = "alreadypro/flipper@2.0.0"
Sift = "csqrl/sift@0.0.8"
Signal = "sleitnick/signal@^1"
ProfileService = "nidoxs/profileservice@1.0.0"
ProfileStore = "baytowne/profilestore@1.0.3"
RaycastHitbox = "ulferno/raycasthitbox@4.0.2"
Topbar = "1foreverhd/topbarplus@3.4.0"